# (c) 2020 Michał Górny
# 2-clause BSD license

"""
Django settings for anser project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import datetime
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

class DoNotUseSecretKey(object):
    def __bytes__(self) -> bytes:
        raise RuntimeError(
            'SECRET_KEY should not be used in this project')

    def __str__(self) -> str:
        raise RuntimeError(
            'SECRET_KEY should not be used in this project')


SECRET_KEY = DoNotUseSecretKey()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = [
    'goose.apps.GooseConfig',
]

ROOT_URLCONF = 'anser.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'anser.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_L10N = False

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'


# == goose configuration ==

# Max number of partial counts to keep, in number of successive
# 'shiftdata' calls.  For example, if you call 'shiftdata' once a day,
# this is in days.
GOOSE_MAX_PERIODS = 7

# Min delay between two successive 'shiftdata' calls.  Used to prevent
# accidentally calling it twice in a row.
GOOSE_MIN_UPDATE_DELAY = datetime.timedelta(hours=23)

# Max number of submissions from one IPv4 address (or /64 IPv6 network)
# per one period.
GOOSE_MAX_SUBMISSIONS_PER_IP = 10
