# Generated by Django 3.0.6 on 2020-05-11 07:47

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from goose.models import DataClass


def add_data_classes(apps: migrations.state.StateApps,
                     schema_editor: BaseDatabaseSchemaEditor
                     ) -> None:
    DataClass(
        name='stamp',
        description='Meaningless stamp added in case of no data',
        data_type=DataClass.DataClassType.STRING,
        public=False).save()


class Migration(migrations.Migration):

    dependencies = [
        ('goose', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data_classes),
    ]
