# (c) 2020 Michał Górny
# 2-clause BSD license

# Generated by Django 3.0.6 on 2020-05-20 13:20

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def convert_to_age(apps: migrations.state.StateApps,
                   schema_editor: BaseDatabaseSchemaEditor
                   ) -> None:
    Count = apps.get_model('goose', 'Count')
    times = sorted(frozenset(x['inclusion_time'] for x
                             in Count.objects.all()
                             .values('inclusion_time')))
    for i, dt in enumerate(reversed(times)):
        Count.objects.filter(inclusion_time=dt).update(age=i+1)


class Migration(migrations.Migration):

    dependencies = [
        ('goose', '0003_add_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='age',
            field=models.IntegerField(default=0,
                                      help_text='Age of data'),
        ),
        migrations.RunPython(convert_to_age),
        migrations.RemoveConstraint(
            model_name='count',
            name='unique_count',
        ),
        migrations.RemoveField(
            model_name='count',
            name='inclusion_time',
        ),
        migrations.AddConstraint(
            model_name='count',
            constraint=models.UniqueConstraint(fields=('value', 'age'),
                                               name='unique_count'),
        ),
    ]
